#!/usr/bin/env bash

# Update package index and install necessary tools
sudo apt update
sudo apt install -y software-properties-common

# Add Ansible repository and update package index again
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt update

# Install Ansible
sudo apt install -y ansible
# Install git
sudo apt install -y git
# Install make
sudo apt install -y make

# Clone Ansible bootcamp repository into the current directory
git clone https://github.com/ppp3ppj/ansible-bootcamp "$PWD"/ansible-bootcamp
