#!/usr/bin/env bash
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
git clone https://github.com/ppp3ppj/ansible-bootcamp $1
